services:
  api:
    build: .
    restart: always
    ports:
    - "8080:8080"
    env_file: .env
    volumes:
    - /etc/localtime:/etc/localtime:ro
    networks:
    - database

networks:
  database:
    external: true
